CREATE TABLE IF NOT EXISTS llm_providers (
  provider_key TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  provider_type TEXT NOT NULL,
  credential_provider TEXT,
  enabled BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS llm_models (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_key TEXT NOT NULL REFERENCES llm_providers(provider_key) ON DELETE CASCADE,
  model_key TEXT NOT NULL,
  display_name TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  llm_metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT uq_llm_models_model_key UNIQUE (model_key)
);

CREATE INDEX IF NOT EXISTS ix_llm_models_provider_sort
  ON llm_models(provider_key, sort_order, model_key);

INSERT INTO llm_providers (
  provider_key,
  display_name,
  provider_type,
  credential_provider,
  enabled,
  sort_order,
  metadata_json
)
VALUES
  (
    'openai',
    'OpenAI',
    'hosted',
    'openai',
    true,
    1,
    '{"docs_url": "https://platform.openai.com/docs/models"}'::jsonb
  ),
  (
    'anthropic',
    'Anthropic',
    'hosted',
    'anthropic',
    true,
    2,
    '{"docs_url": "https://docs.anthropic.com/en/docs/about-claude/models"}'::jsonb
  ),
  (
    'google_gemini',
    'Google Gemini',
    'hosted',
    'google_gemini',
    true,
    3,
    '{"docs_url": "https://ai.google.dev/gemini-api/docs/models"}'::jsonb
  ),
  (
    'ollama',
    'Ollama',
    'local',
    NULL,
    true,
    4,
    '{"base_url_env": "OLLAMA_BASE_URL"}'::jsonb
  ),
  (
    'llama_cpp',
    'llama.cpp',
    'local',
    NULL,
    true,
    5,
    '{"base_url_env": "LLAMA_CPP_BASE_URL"}'::jsonb
  )
ON CONFLICT (provider_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  provider_type = EXCLUDED.provider_type,
  credential_provider = EXCLUDED.credential_provider,
  enabled = EXCLUDED.enabled,
  sort_order = EXCLUDED.sort_order,
  metadata_json = EXCLUDED.metadata_json;

INSERT INTO llm_models (
  provider_key,
  model_key,
  display_name,
  enabled,
  sort_order,
  llm_metadata_json
)
VALUES
  (
    'openai',
    'openai/gpt-4o-mini',
    'GPT-4o mini',
    true,
    1,
    '{
      "schema_version": 1,
      "capabilities": {"streaming": true, "tool_calling": true, "json_mode": true},
      "parameters": {
        "temperature": {"supported": true, "default": 0.7, "min": 0, "max": 2},
        "max_tokens": {"supported": true, "default": 4096, "min": 1, "max": 16384}
      },
      "pricing": {"currency": "USD", "input_per_1m_tokens": 0.15, "output_per_1m_tokens": 0.60}
    }'::jsonb
  ),
  (
    'openai',
    'openai/gpt-4o',
    'GPT-4o',
    true,
    2,
    '{
      "schema_version": 1,
      "capabilities": {"streaming": true, "tool_calling": true, "json_mode": true},
      "parameters": {
        "temperature": {"supported": true, "default": 0.7, "min": 0, "max": 2},
        "max_tokens": {"supported": true, "default": 4096, "min": 1, "max": 16384}
      },
      "pricing": {"currency": "USD", "input_per_1m_tokens": 2.50, "output_per_1m_tokens": 10.00}
    }'::jsonb
  ),
  (
    'openai',
    'openai/gpt-5',
    'GPT-5',
    true,
    3,
    '{
      "schema_version": 1,
      "capabilities": {"streaming": true, "tool_calling": true, "json_mode": true},
      "parameters": {
        "temperature": {"supported": false, "default": null, "min": null, "max": null},
        "max_tokens": {"supported": true, "default": 4096, "min": 1, "max": 128000}
      },
      "pricing": {"currency": "USD", "input_per_1m_tokens": 1.25, "output_per_1m_tokens": 10.00}
    }'::jsonb
  ),
  (
    'anthropic',
    'anthropic/claude-3-5-sonnet-20241022',
    'Claude 3.5 Sonnet',
    true,
    10,
    '{
      "schema_version": 1,
      "capabilities": {"streaming": true, "tool_calling": true, "json_mode": true},
      "parameters": {
        "temperature": {"supported": true, "default": 0.7, "min": 0, "max": 1},
        "max_tokens": {"supported": true, "default": 4096, "min": 1, "max": 8192}
      },
      "pricing": {"currency": "USD", "input_per_1m_tokens": 3.00, "output_per_1m_tokens": 15.00}
    }'::jsonb
  ),
  (
    'google_gemini',
    'gemini/gemini-2.5-flash',
    'Gemini 2.5 Flash',
    true,
    20,
    '{
      "schema_version": 1,
      "capabilities": {"streaming": true, "tool_calling": true, "json_mode": true},
      "parameters": {
        "temperature": {"supported": true, "default": 0.7, "min": 0, "max": 2},
        "max_tokens": {"supported": true, "default": 4096, "min": 1, "max": 65536}
      },
      "pricing": {"currency": "USD", "input_per_1m_tokens": 0.30, "output_per_1m_tokens": 2.50}
    }'::jsonb
  ),
  (
    'ollama',
    'ollama/llama3.1',
    'Llama 3.1',
    true,
    30,
    '{
      "schema_version": 1,
      "capabilities": {"streaming": true, "tool_calling": false, "json_mode": false},
      "parameters": {
        "temperature": {"supported": true, "default": 0.7, "min": 0, "max": 2},
        "max_tokens": {"supported": true, "default": 4096, "min": 1, "max": 32768}
      },
      "pricing": {"currency": "USD", "input_per_1m_tokens": 0, "output_per_1m_tokens": 0}
    }'::jsonb
  )
ON CONFLICT (model_key) DO UPDATE SET
  provider_key = EXCLUDED.provider_key,
  display_name = EXCLUDED.display_name,
  enabled = EXCLUDED.enabled,
  sort_order = EXCLUDED.sort_order,
  llm_metadata_json = EXCLUDED.llm_metadata_json;
